dist: trusty
sudo: true

addons:
  apt:
    packages:
    - sshpass
    
env:
  global:
    - secure: "sA7Nm2RwYyUwkeee6zO4ZSyIi2x90IdrMW104xBi74J2WX2GNuEVZ4Mki17PVFcchuwab4fuNP9DR2ieFn02j6pouhuuSziodLS5qsyPHcwe88nCCVVeQaGAR9Y7xE/XP6J22z/FHj2H730SotQe2HN5zNwcEAtAGsMgcH1Qq21/flhBvW1+t/GEJK4fzKs53z1jsQ0xMTgzpiQZUc3Fdsoed/vcs23QBsN/gz96293dIMDvRgUNfmHebhjc0GkG9mGFj+d+PjQhelTOyuShQdMO9GTEdcDsGWWEeLFl/kLJPD3z8ARUOs+55NRI4bmDLRG/tSFDSf7ke8EhhIVRGeM2E5bj5sfcy4EeJ8LtSO2UE7OR3+EyI3IEpmCyiUUnnmVpAqqWG8XGEyPk0GG0UNnPRJkzq51LQSMutHG/4yW1Oz1DPmsKFF+fyhOZQlyf8KlijVlwD1d5i98K53cmSBmvvR5AWZHvaI28nxTdPluHMXgrv47V9CrdHvwdX4ZR6O3KRW5aCi71cqPN9DU57EgEPasU76c5+rAbgJyiMCinpNp1TG4tHftSALdmZDGPTtx60rYm0dM5qsq/rnxIVzM77nGNJBfeFY0WT2Bl3XcT1vCsbBlSe1nylARNw+Q1ymAxZt0WzOB+ystSoyXRnOGtBCWVYkRozofhk6PVatQ="
  matrix:
#    - OS=centos-7-x64
    - OS=centos-8-x64


before_install:
  - test/setup/setup-server.sh $API_TOKEN $OS
 
script:
  - test/setup/test-server.sh test_actions_user
  - test/setup/test-server.sh test_actions_cron
  - test/setup/test-server.sh test_actions_ip
  - test/setup/test-server.sh test_actions_web
  - test/setup/test-server.sh test_actions_db
  - test/setup/test-server.sh test_actions_dns
  - test/setup/test-server.sh test_actions_ipv6
  - test/setup/test-server.sh test_actions_web_ipv6
  - test/setup/test-server.sh test_actions_dns_ipv6
  - test/setup/test-server.sh test_actions_rebuild_conf
  - test/setup/test-server.sh test_actions_backup
  - test/setup/test-server.sh test_actions_delete
  
after_script:
 # - test/setup/test-coverage.sh
  - test/setup/delete-server.sh $API_TOKEN